#lane_control/lane_controller_node
v_bar: 0.19
k_d:  -3 #-1.5
k_theta:  -6 #-3
k_Id: -3 #-1.0
k_Iphi: 0

k_Dd: 0
k_Dphi: 0

derivative_smoothing: 0.9

theta_thres_max: 0.4
theta_thres_min: -0.4
d_thres: 0.2615
d_offset: -0.02

omega_ff: 0

integral_bounds:
  d:
    top: 0.3
    bot: -0.3
  phi:
    top: 1.2
    bot: -1.2

d_resolution: 0.011
phi_resolution: 0.051

stop_line_slowdown:
  start: 0.4
  end: 0.1

verbose: 0
