# Initial state of the FSM

initial_state: "NORMAL_JOYSTICK_CONTROL"

events: # Maps from subscribing topic to signal ids
  joystick_override_on:
    topic: "joy_mapper_node/joystick_override"
    msg_type: "BoolStamped"
    trigger: True
  joystick_override_off:
    topic: "joy_mapper_node/joystick_override"
    msg_type: "BoolStamped"
    trigger: False
  target_specified:
    topic: "target_selection_node/target_specified"
    msg_type: "BoolStamped"
    trigger: True
  at_stop_line:
    topic: "stop_line_filter_node/at_stop_line"
    msg_type: "BoolStamped"
    trigger: True
  stop_sign_intersection_go:
    topic: "unicorn_intersection_node/intersection_go"
    msg_type: "BoolStamped"
    trigger: True
  traffic_light_intersection_go:
    topic: "communication_node/intersection_go"
    msg_type: "BoolStamped"
    trigger: True
  intersection_done: ## closed loop new
    topic: "intersection_navigation_node/intersection_done"
    msg_type: "BoolStamped"
    trigger: True
  target_reached:
    topic: "graph_planner_node/arrived_at_target"
    msg_type: "BoolStamped"
    trigger: True
  transition_completed:
    topic: "unicorn_intersection_node/transition_done"
    msg_type: "BoolStamped"
    trigger: True


# Define nodes
nodes:
  anti_instagram: "anti_instagram_node/switch"
  led_emitter_node: "led_emitter_node/switch"
  line_detector_node: "line_detector_node/switch"
  lane_filter_node: "lane_filter_node/switch"
  stop_line_filter_node: "stop_line_filter_node/switch"
  unicorn_intersection_node: "unicorn_intersection_node/switch"
  lane_controller_node: "lane_controller_node/switch"
  random_april_tag_turns_node: "random_april_tag_turns_node/switch"
  intersection_type_detector_node: "intersection_type_detector_node/switch"
  graph_planner_node: "graph_planner_node/switch"
  target_selection_node: "target_selection_node/switch"
  ekf_localization_node: "ekf_localization_node/switch"
  deadreckoning_node: "deadreckoning_node/switch"


# Define state transitions

global_transitions:
  joystick_override_on: "NORMAL_JOYSTICK_CONTROL"

states:
  NORMAL_JOYSTICK_CONTROL:
    transitions:
      joystick_override_off: "IDLE"
    active_nodes:
      - lane_filter_node
      - line_detector_node
      - stop_line_filter_node
      - ground_projection_node
      - anti_instagram
      - ekf_localization_node
      - intersection_type_detector_node
      - deadreckoning_node
    lights: "GREEN"

  IDLE:
    transitions:
      target_specified: "LANE_FOLLOWING"
    active_nodes:
      - target_selection_node
      - graph_planner_node
      - ekf_localization_node
    lights: "WHITE"


  LANE_FOLLOWING:
    transitions:
      at_stop_line: "STOP_SIGN_INTERSECTION"
      target_reached: "IDLE"
    active_nodes:
      - anti_instagram
      - line_detector_node
      - ground_projection_node
      - lane_filter_node
      - lane_controller_node
      - stop_line_filter_node
      - unicorn_intersection_node
      - graph_planner_node
      - ekf_localization_node
    lights: "RED"

  STOP_SIGN_INTERSECTION:
    transitions:
      stop_sign_intersection_go: "INTERSECTION_CONTROL"
    active_nodes:
      - anti_instagram
      - intersection_type_detector_node
      - random_april_tag_turns_node
      - stop_line_filter_node
      - unicorn_intersection_node
      - graph_planner_node
      - ekf_localization_node
    lights: "WHITE"

  INTERSECTION_CONTROL:
    transitions:
      intersection_done: "LANE_FOLLOWING"
    active_nodes:
      - line_detector_node
      - lane_filter_node
      - lane_controller_node
      - unicorn_intersection_node
      - graph_planner_node
      - ekf_localization_node

  TRANSITION:
    transitions:
      transition_completed: "LANE_FOLLOWING"
      target_reached: "IDLE"
    active_nodes:
      - anti_instagram
      - line_detector_node
      - ground_projection_node
      - lane_filter_node
      - lane_controller_node
      - unicorn_intersection_node
      - graph_planner_node
      - ekf_localization_node
    lights: "RED"
